name: Gatsby Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.GP_ACCESS_TOKEN }}
          working-dir: my_small_recipe_book
          deploy-branch: public-gh-pages
          gatsby-args: --prefix-paths
